// Lista de palavras para o Nível 1: sem acentos, sem "ç" e em ordem alfabética
const palavrasNivel1 = [
    "ALTO",
    "AMIGO",
    "AMOR",
    "ANEL",
    "ANO",
    "ARROZ",
    "AZUL",
    "BALDE",
    "BICO",
    "BODE",
    "BOLA",
    "BOLO",
    "BOLSA",
    "BRINCO",
    "CAIXA",
    "CAMA",
    "CARNE",
    "CARRO",
    "CASA",
    "CHUVA",
    "CINTO",
    "COPO",
    "DADO",
    "DATA",
    "DEDO",
    "DEZ",
    "DIA",
    "DOCE",
    "DONO",
    "DURO",
    "ELA",
    "ELE",
    "ERRO",
    "ESCOLA",
    "FESTA",
    "FILA",
    "FILME",
    "FLOR",
    "FOGO",
    "FORTE",
    "FOTO",
    "FRASE",
    "FRIO",
    "FRUTA",
    "GALO",
    "GARFO",
    "GATO",
    "GENTE",
    "GRUPO",
    "HARMONIA",
    "HOJE",
    "HORA",
    "HUMILDADE",
    "IGREJA",
    "IMPORTANTE",
    "INTERNET",
    "JANELA",
    "JARDIM",
    "JEITO",
    "JOGO",
    "JUSTO",
    "KETCHUP",
    "KILO",
    "LAGO",
    "LATA",
    "LIMPO",
    "LIVRO",
    "LOJA",
    "LUA",
    "LUTA",
    "LUZ",
    "MALA",
    "MAPA",
    "MAR",
    "MEDO",
    "MESA",
    "MOLHO",
    "MOTO",
    "MUNDO",
    "MUSEU",
    "NADA",
    "NARIZ",
    "NAVIO",
    "NEVE",
    "NOITE",
    "NOME",
    "NOTA",
    "NOVELA",
    "OLHO",
    "ONDA",
    "ONZE",
    "OURO",
    "OVO",
    "PATO",
    "PEDRA",
    "PEIXE",
    "PERNA",
    "PLANO",
    "PONTO",
    "PORCO",
    "PORTA",
    "PRATO",
    "QUARTO",
    "QUASE",
    "QUEDA",
    "QUEIJO",
    "RATO",
    "REDE",
    "REI",
    "RICO",
    "RODA",
    "ROSA",
    "ROSTO",
    "RUA",
    "SALA",
    "SAPO",
    "SEDE",
    "SETE",
    "SINAL",
    "SINO",
    "SONO",
    "SORTE",
    "SUCO",
    "TARDE",
    "TELA",
    "TEMPO",
    "TESTE",
    "TETO",
    "TIPO",
    "TINTA",
    "TUDO",
    "URSO",
    "UVA",
    "VACA",
    "VALE",
    "VARAL",
    "VASO",
    "VELA",
    "VENTO",
    "VERDE",
    "VEZ",
    "VIDA",
    "VINHO",
    "VIVO",
    "XADREZ",
    "XAXADO",
    "XERETAR",
    "XOTE",
    "ZEBRA",
    "ZERO"
];

// Lista para o Nível 2 (case-sensitive e ordenada)
const palavrasNivel2 = [
    "Abril",
    "adeus",
    "agora",
    "Agosto",
    "ajuda",
    "ALEGRIA",
    "ALMA",
    "Amor",
    "AMIZADE",
    "ANTES",
    "aprender",
    "aqui",
    "Aracaju",
    "AZUL",
    "BAIXO",
    "Boa noite",
    "Boa tarde",
    "Bom dia",
    "branco",
    "Brasil",
    "calma",
    "caminho",
    "Cantar",
    "cedo",
    "CELULAR",
    "certo",
    "CHUVA",
    "cidade",
    "COLUNA",
    "COMPUTADOR",
    "correr",
    "depois",
    "DEUS",
    "Dezembro",
    "DIGITAR",
    "Domingo",
    "Escola",
    "escrever",
    "esquerda",
    "FAZENDA",
    "FELICIDADE",
    "feliz",
    "Festa",
    "Fevereiro",
    "flor",
    "FOCO",
    "frio",
    "garfo",
    "gentil",
    "habilidade",
    "hoje",
    "IMAGEM",
    "importante",
    "INTERNET",
    "Janeiro",
    "jovem",
    "Julho",
    "Junho",
    "largo",
    "longe",
    "lugar",
    "Maio",
    "MODELO",
    "mulher",
    "MUNDO",
    "NATUREZA",
    "Novembro",
    "NUNCA",
    "Obrigado",
    "ontem",
    "Outubro",
    "palavra",
    "pequeno",
    "perto",
    "pessoa",
    "planta",
    "Por favor",
    "preto",
    "quando",
    "QUANTO",
    "Quarta",
    "Quinta",
    "quero",
    "resposta",
    "SAPATO",
    "segunda",
    "Sergipe",
    "Setembro",
    "SEXTA",
    "sol",
    "TECLADO",
    "TELEVISOR",
    "tempo",
    "trabalho",
    "verde",
    "vermelho",
    "VIDA",
    "viajar",
    "XADREZ",
    "zero"
];

// Lista para o Nível 3 (com acentos) 
const palavrasNivel3 = [
    "AÇÚCAR",
    "AÇÃO",
    "ÁGUA",
    "BALÃO",
    "BÊNÇÃO",
    "CAFÉ",
    "CAMINHÃO",
    "CANÇÃO",
    "CÉU",
    "CHÃO",
    "CORAÇÃO",
    "CRIANÇA",
    "DIREÇÃO",
    "EMOÇÃO",
    "ESTÔMAGO",
    "FAMÍLIA",
    "FÁCIL",
    "FUMAÇA",
    "FUNÇÃO",
    "HISTÓRIA",
    "IRMÃO",
    "JAPONÊS",
    "LIÇÃO",
    "LÍNGUA",
    "MÁGICO",
    "MÃO",
    "MAÇÃ",
    "MEMÓRIA",
    "MÚSICA",
    "NAÇÃO",
    "ÓCULOS",
    "ÓRGÃO",
    "OPINIÃO",
    "PAÍS",
    "PALÁCIO",
    "PÃO",
    "PÁSSARO",
    "PÉS",
    "PORTUGUÊS",
    "PÚBLICO",
    "QUILÔMETRO",
    "RAZÃO",
    "RELÓGIO",
    "SAÚDE",
    "SÉRIE",
    "SOFÁ",
    "SOLUÇÃO",
    "TERÇO",
    "VILÃO",
    "VITÓRIA"
];

// Lista para o Nível 4 (ditados com frases)
const palavrasNivel4 = [
    "A ignorância é a mãe de todas as doenças.",
    "A palavra é prata, o silêncio é ouro.",
    "A santo que não conheço, não rezo nem ofereço.",
    "Água e conselho só se dão a quem pede.",
    "Antes calar que mal falar.",
    "Apressado come cru.",
    "Cada macaco no seu galho",
    "Casa de ferreiro, espeto de pau.",
    "Deus ajuda quem cedo madruga.",
    "Em terra de cego, quem tem um olho e rei.",
    "Errar é humano, mas insistir no erro é burrice.",
    "Faça o bem sem olhar a quem.",
    "Filho de peixe, peixinho é.",
    "Mais vale um pássaro na mão do que dois voando.",
    "Mentira tem perna curta.",
    "Onde há fumaça, há fogo.",
    "Para bom entendedor, meia palavra basta.",
    "Quem fala o que quer, ouve o que não quer.",
    "Quem tem boca vai a Roma.",
    "Rapadura é doce, mas não é mole não.",
    "Água mole em pedra dura tanto bate até que fura.",
    "Antes só do que mal acompanhado.",
    "Cão que ladra não morde.",
    "Devagar se vai ao longe.",
    "Diz-me com quem andas e te direi quem és.",
    "Mais vale prevenir do que remediar.",
    "Nem tudo que reluz é ouro.",
    "O barato sai caro.",
    "Quem espera sempre alcança.",
    "Quem não arrisca não petisca."
];

// Lista para o Nível 5 (com números e operações) serão constantes fora desse script

// Lista para o Nível 6 (com frases e números)
const palavrasNivel6 = [
    "Adorei a nossa conversa.",
    "Boa noite e durma bem.",
    "Bom dia, como você está?",
    "Como posso ajudar você hoje?",
    "Desejo sucesso para você!",
    "Fique à vontade para perguntar.",
    "Muito obrigado por tudo.",
    "Nos vemos em breve!",
    "Oi, tudo bem?",
    "Parabéns pelo seu esforço!",
    "Que ano você nasceu? XXXX",
    "Que data é hoje? XX/XX/XXXX",
    "Que dia da semana é hoje?",
    "Que mês estamos? XX",
    "Que horas são? XX:XX",
    "Tenha um ótimo dia!",
    "Tenha uma excelente semana!",
    "Tudo vai dar certo!",
    "Você foi muito bem!",
    "Você tem alguma dúvida?"
];